% Purpose: Load and preprocess the dataset, save the processed data for further analysis.

%% Load Data
data = readtable('data/online+shoppers+purchasing+intention+dataset/online_shoppers_intention.csv');

%% Add Variable Descriptions
data.Properties.VariableDescriptions = {
    'Number of administrative pages visited by the user', ...
    'Total time spent on administrative pages in seconds', ...
    'Number of informational pages visited by the user', ...
    'Total time spent on informational pages in seconds', ...
    'Number of product-related pages visited by the user', ...
    'Total time spent on product-related pages in seconds', ...
    'Percentage of visitors who bounce from this page', ...
    'Percentage of sessions that exit from this page', ...
    'Average value attributed to this page in e-commerce transactions', ...
    'Closeness of the visit date to a special holiday', ...
    'Month of the visit', ...
    'Operating system used by the visitor', ...
    'Browser used by the visitor', ...
    'Geographical region of the visitor', ...
    'Type of traffic that led the visitor to the site', ...
    'Visitor type (new or returning)', ...
    'Indicates if the session occurred on a weekend', ...
    'Indicates whether a transaction (revenue) occurred'
};

%% Data Preprocessing
% Convert variables to categorical types where appropriate
data.Month = categorical(data.Month);
data.Region = categorical(data.Region);
data.TrafficType = categorical(data.TrafficType);
data.VisitorType = categorical(data.VisitorType);
data.OperatingSystems = categorical(data.OperatingSystems);
data.Browser = categorical(data.Browser);
data.Weekend = categorical(double(strcmp(data.Weekend, 'TRUE')));
data.Revenue = categorical(double(strcmp(data.Revenue, 'TRUE')));
data.SpecialDay = categorical(data.SpecialDay);

% Rename variables for easier access
data = renamevars(data, {'Administrative_Duration','Informational_Duration', 'ProductRelated_Duration'}, ...
    {'AdministrativeDuration', 'InformationalDuration', 'ProductRelatedDuration'});

% Subsample data to 1000 rows for efficiency
rng(100); % Set seed for reproducibility
numRows = height(data);
randomIndices = randperm(numRows, 1000);
data = data(randomIndices, :);

%% Save Processed Data
save('data/matlab_datasets/processed_dataset.mat', 'data');
