%% Import data
data = readtable('data/online+shoppers+purchasing+intention+dataset/online_shoppers_intention.csv');
head(data);

% Adding descriptions to each variable in the table "data"
data.Properties.VariableDescriptions = {
    'The number of administrative pages visited by the user', ...
    'The total time spent on administrative pages in seconds', ...
    'The number of informational pages visited by the user', ...
    'The total time spent on informational pages in seconds', ...
    'The number of product-related pages visited by the user', ...
    'The total time spent on product-related pages in seconds', ...
    'The percentage of visitors who bounce from this page', ...
    'The percentage of sessions that exit from this page', ...
    'The average value attributed to this page in e-commerce transactions', ...
    'Closeness of the visit date to a special holiday', ...
    'The month of the visit', ...
    'Operating system used by the visitor', ...
    'Browser used by the visitor', ...
    'Geographical region of the visitor', ...
    'Type of traffic that led the visitor to the site', ...
    'Visitor type (new or returning)', ...
    'Indicates if the session occurred on a weekend', ...
    'Indicates whether a transaction (revenue) occurred'
};


%% Data Preprocessing
data.Month = categorical(data.Month);
data.Region = categorical(data.Region)
data.TrafficType = categorical(data.TrafficType)
data.VisitorType = categorical(data.VisitorType)
data.OperatingSystems = categorical(data.OperatingSystems)
data.Browser = categorical(data.OperatingSystems)
data.Weekend = categorical(double(strcmp(data.Weekend, 'TRUE')));
data.Revenue = categorical(double(strcmp(data.Revenue, 'TRUE')));
data.SpecialDay = categorical(data.SpecialDay);
data = renamevars(data, {'Administrative_Duration','Informational_Duration', 'ProductRelated_Duration'}, ...
    {'AdministrativeDuration', 'InformationalDuration', 'ProductRelatedDuration'})

%% Dataset subsample to 1000 obs

rng(100);  % Set a seed to get the same subsample each time
n = 1000;
numRows = height(data);
randomIndices = randperm(numRows, n);
data = data(randomIndices, :);

%% Data Summary

summary(data)


%% Data export

save('data/matlab_datasets/processed_dataset', 'data');

%%
